// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.product;

import co.qcsc.spatha.domain.product.ProductClientDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductClientDataOnDemand_Roo_Configurable {
    
    declare @type: ProductClientDataOnDemand: @Configurable;
    
}
