// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.product;

import co.qcsc.spatha.db.product.ProductClientRepository;
import co.qcsc.spatha.domain.product.ProductClientDataOnDemand;
import co.qcsc.spatha.domain.product.ProductClientIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductClientIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductClientIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductClientIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductClientIntegrationTest: @Transactional;
    
    @Autowired
    ProductClientDataOnDemand ProductClientIntegrationTest.dod;
    
    @Autowired
    ProductClientRepository ProductClientIntegrationTest.productClientRepository;
    
    @Test
    public void ProductClientIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", dod.getRandomProductClient());
        long count = productClientRepository.count();
        Assert.assertTrue("Counter for 'ProductClient' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductClientIntegrationTest.testFind() {
        ProductClient obj = dod.getRandomProductClient();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to provide an identifier", id);
        obj = productClientRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ProductClient' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductClient' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductClientIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", dod.getRandomProductClient());
        long count = productClientRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductClient', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductClient> result = productClientRepository.findAll();
        Assert.assertNotNull("Find all method for 'ProductClient' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductClient' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductClientIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", dod.getRandomProductClient());
        long count = productClientRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductClient> result = productClientRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ProductClient' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductClient' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductClientIntegrationTest.testFlush() {
        ProductClient obj = dod.getRandomProductClient();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to provide an identifier", id);
        obj = productClientRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ProductClient' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductClient(obj);
        Integer currentVersion = obj.getVersion();
        productClientRepository.flush();
        Assert.assertTrue("Version for 'ProductClient' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductClientIntegrationTest.testSaveUpdate() {
        ProductClient obj = dod.getRandomProductClient();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to provide an identifier", id);
        obj = productClientRepository.findOne(id);
        boolean modified =  dod.modifyProductClient(obj);
        Integer currentVersion = obj.getVersion();
        ProductClient merged = productClientRepository.save(obj);
        productClientRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductClient' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductClientIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", dod.getRandomProductClient());
        ProductClient obj = dod.getNewTransientProductClient(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductClient' identifier to be null", obj.getId());
        try {
            productClientRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        productClientRepository.flush();
        Assert.assertNotNull("Expected 'ProductClient' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductClientIntegrationTest.testDelete() {
        ProductClient obj = dod.getRandomProductClient();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductClient' failed to provide an identifier", id);
        obj = productClientRepository.findOne(id);
        productClientRepository.delete(obj);
        productClientRepository.flush();
        Assert.assertNull("Failed to remove 'ProductClient' with identifier '" + id + "'", productClientRepository.findOne(id));
    }
    
}
