// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.product;

import co.qcsc.spatha.db.product.SpecialtyRepository;
import co.qcsc.spatha.domain.product.SpecialtyDataOnDemand;
import co.qcsc.spatha.domain.product.SpecialtyIntegrationTest;
import co.qcsc.spatha.service.product.SpecialtyService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SpecialtyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SpecialtyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SpecialtyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SpecialtyIntegrationTest: @Transactional;
    
    @Autowired
    SpecialtyDataOnDemand SpecialtyIntegrationTest.dod;
    
    @Autowired
    SpecialtyService SpecialtyIntegrationTest.specialtyService;
    
    @Autowired
    SpecialtyRepository SpecialtyIntegrationTest.specialtyRepository;
    
    @Test
    public void SpecialtyIntegrationTest.testCountAllSpecialtys() {
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", dod.getRandomSpecialty());
        long count = specialtyService.countAllSpecialtys();
        Assert.assertTrue("Counter for 'Specialty' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SpecialtyIntegrationTest.testFindSpecialty() {
        Specialty obj = dod.getRandomSpecialty();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to provide an identifier", id);
        obj = specialtyService.findSpecialty(id);
        Assert.assertNotNull("Find method for 'Specialty' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Specialty' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SpecialtyIntegrationTest.testFindAllSpecialtys() {
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", dod.getRandomSpecialty());
        long count = specialtyService.countAllSpecialtys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Specialty', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Specialty> result = specialtyService.findAllSpecialtys();
        Assert.assertNotNull("Find all method for 'Specialty' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Specialty' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SpecialtyIntegrationTest.testFindSpecialtyEntries() {
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", dod.getRandomSpecialty());
        long count = specialtyService.countAllSpecialtys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Specialty> result = specialtyService.findSpecialtyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Specialty' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Specialty' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SpecialtyIntegrationTest.testFlush() {
        Specialty obj = dod.getRandomSpecialty();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to provide an identifier", id);
        obj = specialtyService.findSpecialty(id);
        Assert.assertNotNull("Find method for 'Specialty' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySpecialty(obj);
        Integer currentVersion = obj.getVersion();
        specialtyRepository.flush();
        Assert.assertTrue("Version for 'Specialty' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpecialtyIntegrationTest.testUpdateSpecialtyUpdate() {
        Specialty obj = dod.getRandomSpecialty();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to provide an identifier", id);
        obj = specialtyService.findSpecialty(id);
        boolean modified =  dod.modifySpecialty(obj);
        Integer currentVersion = obj.getVersion();
        Specialty merged = specialtyService.updateSpecialty(obj);
        specialtyRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Specialty' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SpecialtyIntegrationTest.testSaveSpecialty() {
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", dod.getRandomSpecialty());
        Specialty obj = dod.getNewTransientSpecialty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Specialty' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Specialty' identifier to be null", obj.getId());
        try {
            specialtyService.saveSpecialty(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        specialtyRepository.flush();
        Assert.assertNotNull("Expected 'Specialty' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SpecialtyIntegrationTest.testDeleteSpecialty() {
        Specialty obj = dod.getRandomSpecialty();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Specialty' failed to provide an identifier", id);
        obj = specialtyService.findSpecialty(id);
        specialtyService.deleteSpecialty(obj);
        specialtyRepository.flush();
        Assert.assertNull("Failed to remove 'Specialty' with identifier '" + id + "'", specialtyService.findSpecialty(id));
    }
    
}
