// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.product;

import co.qcsc.spatha.domain.product.SpecialtyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SpecialtyDataOnDemand_Roo_Configurable {
    
    declare @type: SpecialtyDataOnDemand: @Configurable;
    
}
