// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.web.mb;

import co.qcsc.spatha.web.mb.DossierItemFileMB;
import java.io.Serializable;

privileged aspect DossierItemFileMB_Roo_Serializable {
    
    declare parents: DossierItemFileMB implements Serializable;
    
    private static final long DossierItemFileMB.serialVersionUID = 1L;
    
}
