// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.web.mb;

import co.qcsc.spatha.web.mb.DossierMB;
import java.io.Serializable;

privileged aspect DossierMB_Roo_Serializable {
    
    declare parents: DossierMB implements Serializable;
    
    private static final long DossierMB.serialVersionUID = 1L;
    
}
