// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.web.mb;

import co.qcsc.spatha.web.mb.ProductSpecialtyMB;
import java.io.Serializable;

privileged aspect ProductSpecialtyMB_Roo_Serializable {
    
    declare parents: ProductSpecialtyMB implements Serializable;
    
    private static final long ProductSpecialtyMB.serialVersionUID = 1L;
    
}
