// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.web.mb;

import co.qcsc.spatha.web.mb.PurchaseOrderMB;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PurchaseOrderMB_Roo_Configurable {
    
    declare @type: PurchaseOrderMB: @Configurable;
    
}
