// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.web.mb;

import co.qcsc.spatha.web.mb.SpecialtyMB;
import java.io.Serializable;

privileged aspect SpecialtyMB_Roo_Serializable {
    
    declare parents: SpecialtyMB implements Serializable;
    
    private static final long SpecialtyMB.serialVersionUID = 1L;
    
}
