// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.product;

import co.qcsc.spatha.domain.product.ProductClient;

privileged aspect ProductClient_Roo_JavaBean {
    
    public String ProductClient.getCode() {
        return this.code;
    }
    
    public void ProductClient.setCode(String code) {
        this.code = code;
    }
    
}
