// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.dossier;

import co.qcsc.spatha.db.dossier.DossierItemFileRepository;
import co.qcsc.spatha.domain.dossier.DossierItemFileDataOnDemand;
import co.qcsc.spatha.domain.dossier.DossierItemFileIntegrationTest;
import co.qcsc.spatha.service.dossier.DossierItemFileService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DossierItemFileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DossierItemFileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DossierItemFileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DossierItemFileIntegrationTest: @Transactional;
    
    @Autowired
    DossierItemFileDataOnDemand DossierItemFileIntegrationTest.dod;
    
    @Autowired
    DossierItemFileService DossierItemFileIntegrationTest.dossierItemFileService;
    
    @Autowired
    DossierItemFileRepository DossierItemFileIntegrationTest.dossierItemFileRepository;
    
    @Test
    public void DossierItemFileIntegrationTest.testCountAllDossierItemFiles() {
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", dod.getRandomDossierItemFile());
        long count = dossierItemFileService.countAllDossierItemFiles();
        Assert.assertTrue("Counter for 'DossierItemFile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testFindDossierItemFile() {
        DossierItemFile obj = dod.getRandomDossierItemFile();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to provide an identifier", id);
        obj = dossierItemFileService.findDossierItemFile(id);
        Assert.assertNotNull("Find method for 'DossierItemFile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DossierItemFile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testFindAllDossierItemFiles() {
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", dod.getRandomDossierItemFile());
        long count = dossierItemFileService.countAllDossierItemFiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'DossierItemFile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DossierItemFile> result = dossierItemFileService.findAllDossierItemFiles();
        Assert.assertNotNull("Find all method for 'DossierItemFile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DossierItemFile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testFindDossierItemFileEntries() {
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", dod.getRandomDossierItemFile());
        long count = dossierItemFileService.countAllDossierItemFiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DossierItemFile> result = dossierItemFileService.findDossierItemFileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DossierItemFile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DossierItemFile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testFlush() {
        DossierItemFile obj = dod.getRandomDossierItemFile();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to provide an identifier", id);
        obj = dossierItemFileService.findDossierItemFile(id);
        Assert.assertNotNull("Find method for 'DossierItemFile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDossierItemFile(obj);
        Integer currentVersion = obj.getVersion();
        dossierItemFileRepository.flush();
        Assert.assertTrue("Version for 'DossierItemFile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testUpdateDossierItemFileUpdate() {
        DossierItemFile obj = dod.getRandomDossierItemFile();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to provide an identifier", id);
        obj = dossierItemFileService.findDossierItemFile(id);
        boolean modified =  dod.modifyDossierItemFile(obj);
        Integer currentVersion = obj.getVersion();
        DossierItemFile merged = dossierItemFileService.updateDossierItemFile(obj);
        dossierItemFileRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DossierItemFile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testSaveDossierItemFile() {
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", dod.getRandomDossierItemFile());
        DossierItemFile obj = dod.getNewTransientDossierItemFile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DossierItemFile' identifier to be null", obj.getId());
        try {
            dossierItemFileService.saveDossierItemFile(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        dossierItemFileRepository.flush();
        Assert.assertNotNull("Expected 'DossierItemFile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DossierItemFileIntegrationTest.testDeleteDossierItemFile() {
        DossierItemFile obj = dod.getRandomDossierItemFile();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DossierItemFile' failed to provide an identifier", id);
        obj = dossierItemFileService.findDossierItemFile(id);
        dossierItemFileService.deleteDossierItemFile(obj);
        dossierItemFileRepository.flush();
        Assert.assertNull("Failed to remove 'DossierItemFile' with identifier '" + id + "'", dossierItemFileService.findDossierItemFile(id));
    }
    
}
