// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.dossier;

import co.qcsc.spatha.domain.dossier.DossierDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DossierDataOnDemand_Roo_Configurable {
    
    declare @type: DossierDataOnDemand: @Configurable;
    
}
