// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.dossier;

import co.qcsc.spatha.domain.dossier.Dossier;

privileged aspect Dossier_Roo_JavaBean {
    
    public Boolean Dossier.getTemplate() {
        return this.template;
    }
    
    public void Dossier.setTemplate(Boolean template) {
        this.template = template;
    }
    
}
