// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.qcsc.spatha.domain.purchase;

import co.qcsc.spatha.domain.purchase.OrderItemDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OrderItemDataOnDemand_Roo_Configurable {
    
    declare @type: OrderItemDataOnDemand: @Configurable;
    
}
